# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

[tools]
rojo = "rojo-rbx/rojo@7.7.0"
luau-lsp = "JohnnyMorganz/luau-lsp@1.68.1"
wally = "UpliftGames/wally@0.3.2"
stylua = "JohnnyMorganz/StyLua@2.5.2"
